name: Build and Serve Zola Site

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Zola
      - name: Install Zola
        run: |
          curl -L https://github.com/getzola/zola/releases/download/v0.17.2/zola-v0.17.2-x86_64-unknown-linux-gnu.tar.gz -o zola.tar.gz
          tar -xzf zola.tar.gz
          sudo mv zola /usr/local/bin/zola

      # Build the site
      - name: Build Zola site
        run: zola build

      # Serve the site (optional)
      - name: Serve Zola site
        run: |
          zola serve --interface 0.0.0.0 --port 8080 --base-url http://localhost:8080 &
          echo "Zola site is running at http://localhost:8080"